---
# tasks file for ansible-role-macos-harden

- name: SCORED | 1.1 | Verify all Apple provided software is current
  command: softwareupdate -l
  register: result_1_1
  changed_when: false
  when:
    - macos_cis_rule_1_1
  tags:
    - scored
    - level1
    - section1
    - section1.1

- name: SCORED | 1.1 | Verify all Apple provided software is current
  debug:
    msg: Please check for software updates
  when:
    - macos_cis_rule_1_1
    - result_1_1.rc != 0
  tags:
    - scored
    - level1
    - section1
    - section1.1

- name: SCORED | 1.2 | Enable Auto Update
  osx_defaults:
    domain: com.apple.SoftwareUpdate
    key: AutomaticCheckEnabled
    type: int
    value: 1
  when:
    - macos_cis_rule_1_2
  tags:
    - scored
    - level1
    - section1
    - section1.2

- name: SCORED | 1.3 | Enable app update installs
  osx_defaults:
    domain: com.apple.commerce
    key: AutoUpdate
    type: bool
    value: true
  when:
    - macos_cis_rule_1_3
  tags:
    - scored
    - level1
    - section1
    - section1.3

- name: SCORED | 1.4 | Enable system data files and security update installs
  osx_defaults:
    domain: com.apple.SoftwareUpdate
    key: ConfigDataInstall
    type: bool
    value: true
  when:
    - macos_cis_rule_1_4
  tags:
    - scored
    - level1
    - section1
    - section1.4

- name: SCORED | 1.4 | Enable system data files and security update installs
  osx_defaults:
    domain: com.apple.SoftwareUpdate
    key: CriticalUpdateInstall
    type: bool
    value: true
  when:
    - macos_cis_rule_1_4
  tags:
    - scored
    - level1
    - section1
    - section1.4

- name: SCORED | 1.5 | Enable macOS update installs
  osx_defaults:
    domain: com.apple.SoftwareUpdate
    key: AutoUpdateRestartRequired
    type: bool
    value: true
  when:
    - macos_cis_rule_1_5
  tags:
    - scored
    - level1
    - section1
    - section1.5

- name: SCORED | 2.1.1 | Turn off Bluetooth, if no paired devices exist
  command: defaults read /Library/Preferences/com.apple.Bluetooth ControllerPowerState
  register: result_2_1_1_a
  changed_when: false
  when:
    - macos_cis_rule_2_1_1
  tags:
    - scored
    - level1
    - section2
    - section2.1
    - section2.1.1

- name: SCORED | 2.1.1 | Turn off Bluetooth, if no paired devices exist
  shell: system_profiler SPBluetoothDataType | grep "Bluetooth:" -A 20 | grep Connectable
  register: result_2_1_1_b
  changed_when: false
  when:
    - macos_cis_rule_2_1_1
  tags:
    - scored
    - level1
    - section2
    - section2.1
    - section2.1.1

- name: SCORED | 2.1.1 | Turn off Bluetooth, if no paired devices exist
  osx_defaults:
    domain: com.apple.Bluetooth
    key: ControllerPowerState
    type: int
    value: 0
  when:
    - "result_2_1_1_a.rc == 1 and 'Connectable: Yes' not in result_2_1_1_b.stdout"
    - macos_cis_rule_2_1_1
  tags:
    - scored
    - level1
    - section2
    - section2.1
    - section2.1.1

- name: SCORED | 2.1.1 | Turn off Bluetooth, if no paired devices exist
  command: killall -HUP blued
  when:
    - "result_2_1_1_a.rc == 1 and 'Connectable: Yes' not in result_2_1_1_b.stdout"
    - macos_cis_rule_2_1_1
  tags:
    - scored
    - level1
    - section2
    - section2.1
    - section2.1.1

- name: NOTSCORED | 2.1.2 | Bluetooth "Discoverable" is only available when Bluetooth preference pane is open
  debug:
    msg: Do not leave the Bluetooth System Preference pane open when not necessary
  when:
    - macos_cis_rule_2_1_2
  tags:
    - scored
    - level1
    - section2
    - section2.1
    - section2.1.2

- name: SCORED | 2.1.3 | Show Bluetooth status in menu bar
  osx_defaults:
    domain: com.apple.systemuiserver
    key: menuExtras
    array_add: yes
    value: "/System/Library/CoreServices/Menu Extras/Bluetooth.menu"
  when:
    - macos_cis_rule_2_1_3
  tags:
    - scored
    - level1
    - section2
    - section2.1
    - section2.1.3

- name: SCORED | 2.2.1 | Enable "Set time and date automatically"
  command: systemsetup -getusingnetworktime
  register: result_2_2_1
  changed_when: false
  when:
    - macos_cis_rule_2_2_1
  tags:
    - scored
    - level1
    - section2
    - section2.2
    - section2.2.1

- name: SCORED | 2.2.1 | Enable "Set time and date automatically"
  command: systemsetup -getusingnetworktime
  register: result_2_2_1
  changed_when: false
  when:
    - macos_cis_rule_2_2_1
  tags:
    - scored
    - level1
    - section2
    - section2.2
    - section2.2.1

- name: SCORED | 2.2.1 | Enable "Set time and date automatically"
  command: "systemsetup -setnetworktimeserver {{ macos_cis_rule_2_2_1_timeserver }}"
  when:
    - "result_2_2_1.stdout != 'Network Time: On'"
    - macos_cis_rule_2_2_1
  tags:
    - scored
    - level1
    - section2
    - section2.2
    - section2.2.1

- name: SCORED | 2.2.1 | Enable "Set time and date automatically"
  command: systemsetup –setusingnetworktime on
  when:
    - "result_2_2_1.stdout != 'Network Time: On'"
    - macos_cis_rule_2_2_1
  tags:
    - scored
    - level1
    - section2
    - section2.2
    - section2.2.1

- name: SCORED | 2.2.2 | Ensure time set is within appropriate limits
  debug:
    msg: "*** check manually ***"
  when:
    - macos_cis_rule_2_2_2
  tags:
    - scored
    - level1
    - section2
    - section2.2
    - section2.2.2

- name: SCORED | 2.3.1 | Set an inactivity interval of 20 minutes or less for the screen saver
  osx_defaults:
    domain: com.apple.screensaver
    key: idleTime
    type: int
    value: "{{ macos_cis_rule_2_3_1_screensaver_idle_time }}"
  when:
    - macos_cis_rule_2_3_1
  tags:
    - scored
    - level1
    - section2
    - section2.3
    - section2.3.1

- name: SCORED | 2.3.2 | Secure screen saver corners
  shell: "defaults read {{ home_dir }}/Library/Preferences/com.apple.dock | grep -i corner"
  register: result_2_3_2
  changed_when: false
  when:
    - macos_cis_rule_2_3_2
  tags:
    - scored
    - level1
    - section2
    - section2.3
    - section2.3.2

- name: SCORED | 2.3.2 | Secure screen saver corners
  fail:
    msg: "Setting a hot corner to disable the screen saver poses a potential security risk since an unauthorized person could use this to bypass the login screen and gain access to the system."
  when:
    - "'= 6;' in result_2_3_2.stdout"
    - macos_cis_rule_2_3_2
  tags:
    - scored
    - level1
    - section2
    - section2.3
    - section2.3.2

- name: NOTSCORED | 2.3.3 | Secure screen saver corners
  debug:
    msg: "Please know how to lock the screen. In Mojave, Command-Control-Q is the quickest option."
  when:
    - macos_cis_rule_2_3_3
  tags:
    - notscored
    - level1
    - section2
    - section2.3
    - section2.3.3
